Donatsi2/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import  static
from . import settings
from PermohonanDonasi.views import homepage

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', homepage, name="homepage"), #homepage ntar
    path('tentang-kami/', include("TentangKami.urls", namespace="tentang-kami")),
    path('donasi/', include("PermohonanDonasi.urls", namespace="permohonan")),
    path('donasi/', include("PemberianDonasi.urls", namespace="pemberian")),
    path('user/', include("User.urls", namespace="user")),
    path('login/', include(('Login.urls', 'login'), namespace='login'))
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

PermohonanDonasi/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import daftar_permohonan, list_permohonan, detail_permohonan, getData

app_name = "permohonan"
urlpatterns = [
    path('', list_permohonan, name="list-permohonan"),
    path('getData/', getData, name="get-data"),
    path('<id>', detail_permohonan, name="detail-permohonan"),
    path('daftar/', daftar_permohonan, name="daftar-permohonan"),
]

User/urls.py
from django.contrib import admin
from django.urls import path, include
# from django.contrib.auth import (
#     login, logout
# )

from django.contrib.auth.views import LoginView, LogoutView

from django.conf.urls import url
from . import views
# from django.contrib.auth.views import (
#     login, logout, password_reset, password_reset_done, password_reset_confirm,
#     password_reset_complete
# )

app_name = "user"

urlpatterns = [
    path('register', views.register, name="register"),
    # path('login', LoginView.as_view(template_name='login.html'),name='login'),
    path('logout', LogoutView.as_view(), name='logout'),
    path('profile', views.view_profile, name="view_profile")
]

PermohonanDonasi/models.py
from django.db import models
import django.utils.timezone
from KategoriDonasi.models import Kategori
# from User.models import UserProfile

# Create your models here.

class Permohonan(models.Model):
    KATEGORI = []
    for kategori in Kategori.objects.all():
        KATEGORI.append((kategori.key_kategori, kategori.nama_kategori))


    email = models.EmailField(max_length=100)
    nama_pemohon = models.CharField(max_length=100)
    bank = models.CharField(max_length=100)
    rekening = models.CharField(max_length=100)
    nomor_telp = models.CharField(null=True, max_length=13)
    nama_donasi = models.CharField(max_length=100)
    image_donasi = models.ImageField(upload_to="images/", default="images/donatsi.png")
    target_uang = models.PositiveIntegerField()
    uang_terpenuhi = models.PositiveIntegerField(default=0, null=True)
    deadline = models.DateField(auto_now_add = False)

    pemilik = models.CharField(max_length=100)

    pilihan_kategori_alasan = models.CharField(max_length=100, choices=KATEGORI,
        default='kegiatan_sosial'
    )

    kategori_alasan = models.ForeignKey('KategoriDonasi.Kategori', null=True, on_delete=models.CASCADE)
    urgency = models.PositiveIntegerField(default=0, null=True)
    deskripsi_alasan = models.TextField(max_length=500)
    # comments = models.ForeignKey('Comments.data_comments', on_delete=models.CASCADE, default=None)
    # semua_pemberian = models.ForeignKey('PemberianDonasi.Pemberian', on_delete=models.CASCADE)
    tanggal_pembuatan = models.DateField(default = django.utils.timezone.now)

    def __str__(self):
        return self.nama_donasi
    
    def deskripsi_singkat(self):
        if(len(self.deskripsi_alasan) > 50):
            return self.deskripsi_alasan[:50] + "..."
        return self.deskripsi_alasan

PermohonanDonasi/forms.py
from django import forms
from . import models
from django.utils import timezone
from datetime import datetime


class DateInput(forms.DateInput):
    input_type = "date"


class CreatePermohonan(forms.ModelForm):
    class Meta:
        model = models.Permohonan
        fields = "__all__"
        exclude = ['uang_terpenuhi', 'kategori_alasan', 'urgency', 'comments', 'semua_pemberian', 'tanggal_pembuatan', 'pemilik']

        widgets = {
            "deadline": DateInput,
            "target_uang": forms.TextInput()
        }

    def __init__(self, *args, **kwargs):
        super(CreatePermohonan, self).__init__(*args, **kwargs)

        for fname, f in self.fields.items():
            f.widget.attrs['class'] = 'input'

        self.fields['pilihan_kategori_alasan'].widget.attrs['class'] += ' pilihan-kategori'
        self.fields['nama_donasi'].widget.attrs['class'] += ' nama-donasi'
        self.fields['deskripsi_alasan'].widget.attrs['class'] += ' deskripsi-alasan'
        self.fields['image_donasi'].widget.attrs['class'] += ' image-donasi'


        

# class SearchPermohonan(forms.Form):
#     searched = forms.CharField(max_length=100)

PermohonanDonasi/views.py
from django.shortcuts import render, redirect
from django.core import serializers
from django.http import HttpResponse

from .forms import CreatePermohonan
from KategoriDonasi.models import Kategori
from .models import Permohonan
from Comments.forms import add_comment
from Comments.models import data_comments

from django.contrib.auth.decorators import login_required


import datetime

# Create your views here.
def getData(request):
    permohonan = Permohonan.objects.all()
    permohonan_list = serializers.serialize('json', permohonan)
    return HttpResponse(permohonan_list, content_type="text/json-comment-filtered")
    
def homepage(request):
    recommendations = []
    
    for permohonan in Permohonan.objects.all():
        if permohonan.deadline <= datetime.date.today():
            permohonan.delete()
    
    for i in range(5,0,-1):
        permohonan_query = Permohonan.objects.filter(urgency = i)
        for permohonan in permohonan_query:
            if(len(recommendations) < 6):
                recommendations.append(permohonan)
            else:
                break
        if(len(recommendations) >= 6):
            break

    return render(request,"homepage.html", {"recommendations": recommendations})

@login_required(login_url='/login')
def daftar_permohonan(request):
    form = CreatePermohonan()
    if request.method == "POST":
        form = CreatePermohonan(request.POST, request.FILES)
        if form.is_valid():
            permohonan = form.save(commit=False)
            permohonan.kategori_alasan = Kategori.objects.get(key_kategori=permohonan.pilihan_kategori_alasan)
            permohonan.urgency = permohonan.kategori_alasan.urgency
            permohonan.pemilik = request.user.username
            permohonan.save()
            return redirect("homepage")
    return render(request, "daftar-permohonan.html", {'form': form})

def list_permohonan(request):
    # query = request.GET.get("query")
    # if query:
    #     objects = Permohonan.objects.filter(nama_donasi__contains=query)
    # else:
    #     objects = Permohonan.objects.all()
    
    objects = Permohonan.objects.all()
    for permohonan in objects:
        if permohonan.deadline <= datetime.date.today():
            permohonan.delete()

    return render(request, 'semua-permohonan.html')

# @login_required(login_url='/login')
def detail_permohonan(request, id):
    permohonan = Permohonan.objects.get(id=id)
    if(request.method == "POST"):
        if(not request.user.is_authenticated):
            return redirect("Login:login")
        
        form = add_comment(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.permohonan = permohonan
            comment.pemilik = request.user.username
            comment.save()
            return redirect("permohonan:detail-permohonan", id=id)
    
    form = add_comment()
    comments = data_comments.objects.filter(permohonan=permohonan).order_by("dateTime").reverse()
    return render(request, 'detail-permohonan.html', {"permohonan": permohonan, "comments": comments, "form": form})

PermohonanDonasi/templates/daftar-permohonan.html
{% extends 'base-template.html' %}
{% load static %}

{% block styling %}
<link rel="stylesheet" href="{% static 'daftar-permohonan.css' %}">
{% endblock %}

{% block title %}
Daftar Permohonan
{% endblock %}

{% block content %}
<div id="tk_container">
    <form id="bigform" class="form-daftar col-12" action="" enctype="multipart/form-data" method="post">
        {% csrf_token %}
        <div class="center">
                <div class="form-field">
                    <p>JUDUL DONASI</p>
                    <p> {{ form.nama_donasi }} </p>
                </div>
                <div class="form-field">
                    <p>TIPE DONASI</p>
                    <p>{{ form.pilihan_kategori_alasan }}</p>
                </div>
        </div>
        <div class="center">
            <div class="form-field">
                <p>NAMA PEMOHON</p>
                <p>{{ form.nama_pemohon }}</p>
            </div>
            <div class="form-field">
                <p>EMAIL PEMOHON</p>
                <p>{{ form.email }}</p>
            </div>
        </div>
        <div class="center">
            <div class="form-field">
                <p>NO TELP PEMOHON</p>
                <p>{{ form.nomor_telp }}</p>
            </div>
            <div class="form-field">
                <p>JUMLAH DONASI (Rp)</p>
                <p>{{ form.target_uang }}</p>
            </div>
        </div>
        <div class="center">
            <div class="form-field">
                <p>BANK PEMOHON</p>
                <p>{{ form.bank }}</p>
            </div>
            <div class="form-field">
                <p>NOMOR REKENING</p>
                <p>{{ form.rekening }}</p>
            </div>
        </div>
        <div class="center form-baris-deskripsi">
            <div class="form-field">
                <p>DESKRIPSI DONASI</p>
                <p><input type="text" name="deskripsi_alasan" cols="40" rows="10" maxlength="500" class="input deskripsi-alasan" required="" id="id_deskripsi_alasan" spellcheck="false" ></input></p>
            </div>
        </div>
        <div class="center">
            <div class="form-field">
                <p>DEADLINE</p>
                <p>{{ form.deadline }}</p>
            </div>
            <div class="form-field">
                <p>FOTO</p>
                <p>{{ form.image_donasi }}</p>
            </div>
        </div>

        <input class="submit" type="submit" value="SUBMIT">

    </form>
</div>
{% endblock %}

PermohonanDonasi/templates/detail-permohonan.html
{% extends 'base-template.html' %}
{% block title %}
{{ permohonan.nama_donasi }}
{% endblock %}
{% block content %}
<div id="bg_hijau">

    <div class="center pt-4">
        <h1 id="tulisan_line">{{ permohonan.nama_donasi }}</h1>
    </div>

    <div class="center">
        <img src="{{ permohonan.image_donasi.url }}" alt="image" id="image_donasi">
    </div>

    <div class="center mt-4 ">
            <div id="tulisan_profil">
                    <p><b>Nama pemohon:</b> &emsp; {{ permohonan.nama_pemohon }}</p>
                    <p><b>Email:</b>  &emsp; {{ permohonan.email }}</p>
                    <p><b>Nomor telp:</b> &emsp; {{ permohonan.email }}</p>
            </div>
    </div>

    <div class="center mt-4 pt-4 mb-4 pb-4">
            <div id="tulisan_center">
                    <p>{{ permohonan.deskripsi_alasan }}</p>
                    <h3 id="duit2"> 
                        Rp. {{ permohonan.uang_terpenuhi }} / Rp. {{ permohonan.target_uang }}
                    </h3>
                    <p>
                        Deadline: {{ permohonan.deadline }}
                    </p>
                </div>
    </div>







<div class="comment-section pt-2 pb-4 mb-2" id="komen_form">
    <form action="" method="post">
        {% csrf_token %}

        <div class="center mt-4 pt-4 mb-4">
            <h4>Comments</h4>
        </div>

        <div class="center">
            {{ form.comment }}
        </div>
        
        <div class="center mt-4 pt-4">
            <input class="submit" type="submit" value="Submit">
        </div>
    </form>
</div>


<div class="row mt-4 pt-4 mb-2 pb-2">

        <!-- {% if comments %}
        <div class="row mt-4 pt-4" id="semua_komen">
                {% for comment in comments %}
                <div class="col-xl-3 col-md-4 col-12 p-4 m-4" id="kotak_saran">
                                <p>{{ comment.comment }}</p>
                                <p>{{ comment.pemilik }}</p>
                                <p>{{ comment.dateTime }}</p>    
                </div>
                {% endfor %}
        </div>
        {% endif %} -->


        {% if comments %}
        {% for comment in comments %}

            <div class="col-xl-3 col-md-4 col-12 p-4 m-4 comment" id="kotak_saran">
                    <style>
                        #kotak_saran{
                            color: #031b43;
                        }    
                    </style>

                <h3><b>{{ comment.pemilik }}</b></h4>
                <h5>{{ comment.comment }}</h5>
                <h6>{{ comment.dateTime }}</h6>
            </div>
        {% endfor %}
    {% endif %}

</div>


</div>

{% endblock %}

PermohonanDonasi/templates/semua-permohonan.html
{% extends 'base-template.html' %}
{% load static %}
{% block title %}
List Donasi
{% endblock %}

{% block scripts %}
<script src="{% static 'scripts/getDataSemuaPermohonan.js' %}"></script>
{% endblock %}

{% block content %}
<div id="sp_container">
    <div class="pt-4">
            <div class="center" id="sp_search">
                    <!-- <form method="GET" action="{% url 'permohonan:list-permohonan' %}"> -->
                <div class="search_container">
                        <input id="search_input" class="form-control" type="text" name="query" placeholder="cari donasi...">
                        <div class="center m-4">
                                <input class="submit" type="submit" id="search_submit" value="Search">
                        </div>
                </div>
            </div>
            
            <div class="card-group row ml-4 mr-4" id="sp_result">
            </div>
            
            {% endblock %}


    </div>
        
</div>