Donatsi2/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import  static
from . import settings
from PermohonanDonasi.views import homepage

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', homepage, name="homepage"), #homepage ntar
    path('tentang-kami/', include("TentangKami.urls", namespace="tentang-kami")),
    path('donasi/', include("PermohonanDonasi.urls", namespace="permohonan")),
    path('donasi/', include("PemberianDonasi.urls", namespace="pemberian")),
    path('user/', include("User.urls", namespace="user")),
    path('login/', include(('Login.urls', 'login'), namespace='login'))
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

Login/urls.py
from django.conf.urls import url
from .views import index, homepage, login_view, logout_view

app_name = 'Login'

urlpatterns = [
    url(r'^$', index, name='login'),
    url(r'^validate/$', login_view, name='validate'),
    url(r'^logout/$', logout_view, name='logout')
]

User/urls.py
from django.contrib import admin
from django.urls import path, include
# from django.contrib.auth import (
#     login, logout
# )

from django.contrib.auth.views import LoginView, LogoutView

from django.conf.urls import url
from . import views
# from django.contrib.auth.views import (
#     login, logout, password_reset, password_reset_done, password_reset_confirm,
#     password_reset_complete
# )

app_name = "user"

urlpatterns = [
    path('register', views.register, name="register"),
    # path('login', LoginView.as_view(template_name='login.html'),name='login'),
    path('logout', LogoutView.as_view(), name='logout'),
    path('profile', views.view_profile, name="view_profile")
]

Login/models.py
from django.db import models

# Create your models here.

Login/views.py
from django.shortcuts import render
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, logout, login
from django.contrib.auth.views import auth_login
from django.http import HttpResponseRedirect
from django.urls import reverse

# Create your views here.
response = {
    'author' : 'name'
}

def index(request):
    response['login'] = request.user.is_authenticated
    if request.user.is_authenticated:
        return HttpResponseRedirect(reverse('homepage'))
    else :
        html = 'login.html'
    return render(request, html, response)

def homepage(request):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse('Login:login'))
    else:
        response['login'] = request.user.is_authenticated
        response['username'] = request.user.get_username
        return render(request, 'homepage.html')

def login_view(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        validate = authenticate(username=username, password=password)
        print(validate)
        if validate is not None:
            print("success")
            login(request, validate)
            print(request.user)
            return HttpResponseRedirect(reverse('homepage'))
        else:
            print("username/password wrong or does not exist")
            return HttpResponseRedirect(reverse('Login:login')) 

def logout_view(request):
	logout(request)
	return HttpResponseRedirect(reverse('homepage'))

Login/templates/login.html
{% extends 'base-template.html' %}
<!-- {% load static %}
{% block styling %}
<link rel="stylesheet" href="{% static 'daftar-permohonan.css' %}">
{% endblock %} -->

{% block title %}
Tentang Kami
{% endblock %}
{% block content %}

<div id="tk_container">
    <style>
        #tk_container{
            color: white;
            height: 100vh;
            padding-top: 5rem;
        }

    </style>

<div class="center pt-4 mb-4 pb-4">

        <h1 id="tulisan_line">Login</h1>
</div>

<div class="row center" id="login_attr">
        <div class="col-md-6 col-md-offset-3">
            <div class="rata-tengah">
                <!-- <div class="judul">
                    <p>Login Page</p>
                </div> -->
                <form action="{% url 'login:validate' %}" method="POST">
                    {% csrf_token %}
                    <p>
                        <label for="username"> <i class="fa fa-user" aria-hidden="true"></i> Username </label>
                        <input type="text" id="username" name="username" required>
                    </p>
                    <p>
                        <label for="password"> <i class="fa fa-key" aria-hidden="true"></i> Password</label>
                        <input type="password" id="password" name="password" required>
                    </p>
                    <button type="submit" class="submit">Login</button>
                </form>
                {% comment %} <a href="{% url 'user:register' %}" class="submit"> <i aria-hidden="true"></i> Sign Up </a>   {% endcomment %}
            </div>
        </div>
 
    
</div>

{% endblock %}